version: "3.3"
services:
  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user

  service:
    image: python:3.10
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8001:8001'
    build:
      context: ./
      dockerfile: Dockerfile

volumes:
  app-db-data:
    driver: local

